services:
  - type: web
    name: password-checker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn password_checker.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: password_checker.settings
